name: "ClearWSL Build"

on:
  push:
    branches: [main]
    # Trigger only when Makefile is changed
    paths: ["Makefile"]
  workflow_dispatch:
  schedule:
    # Trigger on the 1st day of every month at 12:00 UTC
    - cron: "0 12 1 * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          ref: "main"
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
      - run: mkdir -p release
      - name: install dependencies
        run: sudo apt install -y curl libarchive-tools jq tar unzip
      - name: build package & make hash
        run: |
          sudo make
          sudo make clean
          sha512sum Clear.zip > Clear.zip.sha512
          mv Clear.zip* release/
      - name: save release as artifact
        uses: actions/upload-artifact@v4
        with:
          retention-days: 10
          path: "release/*"
      - name: upload artifact to release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: True
          prerelease: True
          tag: "action-build"
          omitBody: True
          omitBodyDuringUpdate: True
          omitNameDuringUpdate: True
          artifacts: "release/Clear.zip*"
          token: ${{ secrets.GITHUB_TOKEN }}
