name: "ClearWSL Weekly Build"

on:
  push:
    branches: [ main ]
    # Trigger only when Makefile is changed
    paths: ['Makefile']
  workflow_dispatch:
      inputs:
  schedule:
    # Trigger every Sunday at 23:50 UTC
    - cron: "50 23 * * sun"

jobs:
  build:
    runs-on: ubuntu-latest
    # Skip build with [ci skip] in commit
    if: "! contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
        with:
          ref: 'main'
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
      - run: mkdir -p release
      - name: install dependencies
        run: sudo apt install -y curl libarchive-tools jq tar unzip xz-utils
      - name: build package
        run: |
             sudo make
             sudo make clean
             mv Clear.zip release/Clear.zip
      - name: save release as artifact
        uses: actions/upload-artifact@v3
        with:
          retention-days: 10
          name: Clear.zip
          path: release
